sudo: required
language: go
#services:
#  - docker

go:
  - 1.x

#before_install:
#  - docker-compose -f assets/docker-compose.yml up -d

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/klepto -covermode=count
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: out/klepto
    skip_cleanup: true
    file_glob: true
    on:
      repo: hellofresh/klepto
      tags: true
