sudo: required
language: go

go:
  - 1.x

services:
  - docker

env:
  - TEST_POSTGRES="postgres://hello:fresh@localhost:8050/klepto?sslmode=disable"

before_install:
  - docker-compose up -d

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/klepto -covermode=count
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
