version: "3"

services:

  postgres:
    image: postgres:9.6-alpine
    ports:
      - '8050:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: fresh

  mysql:
    image: mysql:5.5
    ports:
      - '8052:3306'
    environment:
      LC_ALL: C.UTF-8
      MYSQL_ROOT_PASSWORD: hellofresh